SELECT CITY, length(CITY) AS Char_Length
FROM  STATION
ORDER  BY length(CITY) ASC, CITY ASC
LIMIT 1;
SELECT CITY, length(CITY) AS Char_Length
FROM  STATION
ORDER  BY length(CITY) DESC, CITY ASC
LIMIT 1;